version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'animauxdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my-db-1:/var/lib/mysql
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #   command: 'npm run start:dev'
  #   ports:
  #     - '3000:3000'
  #   expose:
  #     - '3000'
volumes:
  my-db-1: